### ISSUE TITLE
Only XHTML files and can we lazyload images?

### ISSUE THREAD

**Issue by UnluckyLuke** [eligrey/hotlink.js#1]
This works really good, better than I thought since it actually worked! Thanks for your work! ;)

I now use Iframes to include the XHTML-files on my site, would it be possible to get this running with a PHP-file (without changing server configs) or is XHTML doing something special that wont work with a normal server running PHP code?

Another quick question, is there any way to lazyload the images with the script, if so, can you point me in the right direction?

**Comment by eligrey** [comment]
hotlink.js does not require XHTML. If you run into any issues using hotlink.js with normal HTML, please submit an issue.

**Comment by eligrey** [comment]
You can combine the `hotlink(img element)` API with other lazy loading libraries to achieve your desired functionality. I'll consider adding built-in lazy loader support as well.

**Comment by UnluckyLuke** [comment]
Thanks for your reply. I did have problems to get things to load when I messed around with it last time but maybe I missed something. I'll check it out once I get back home. Thanks again!
