### ISSUE TITLE
I'm having problems getting this script to work with my site.

### ISSUE THREAD

**Issue by AndreaHasani** [eligrey/hotlink.js#2]
I have a site where I need to load external images and after changing src to data-src nothing shows up. The script is loaded. The images are inserted into the html page on the server. Server is a flask application if that matters.

**Comment by eligrey** [comment]
Are you still experiencing this issue?

**Comment by AndreaHasani** [comment]
No I was stupid af to use href insteed of src. Btw is there any way to implement lazy loading with this? I'm bad at javascript myself.
